### ISSUE TITLE
Баг с быстрым течением времени (первые несколько секунд) из за долгого выполнения setup()

### ISSUE THREAD

**Issue by ke46138** [GyverLibs/GyverDS3231#1]
**Версия библиотеки:**

> 1.0.2

**Какой используется МК**

> Arduino UNO

**Версия Arduino IDE**

> 1.8.19

**Корректно ли работают ли встроенные примеры, в которых используются функции и конструкции, приводящие к багу в вашем коде**

> Да

**Какой код загружался, какая работа от него ожидалась и как он работает в реальности**
```
#include <Arduino.h>
#include <GyverDS3231.h>
GyverDS3231 ds;

void setup() {
    Serial.begin(115200);
    Wire.begin();
    Serial.println("Start");
    if (!ds.begin()) ds.setBuildTime();
    delay(10000);
    Serial.println("After delay");
}

void loop() {
    if (ds.tick()) {
        Serial.println(ds.toString());

        Datime dt(ds);
        Serial.println(dt.second);
        Serial.println(dt.minute);
        // ...
    }
}
```
**Ожидаемая работа кода:**

> Обычный ход времени после setup()

**Видео:**

> https://drive.google.com/file/d/1GSsmZuOUtKEljPhSBYVsyKF8eYIYcJ8W/view?usp=sharing

**Comment by GyverLibs** [comment]
Всё верно, библиотека работает так, чтобы не пропускать секунды при задержках в программе, что критически важно для автоматизации по времени
